#!/usr/bin/env python3
"""Stage 9, step 2 -- build one RooWorkspace + datacard per (mass, function).

Runs on plain PyROOT + stdlib ONLY (no wrplotter / uproot / numpy) so it can --
and should -- be executed inside the combine container: the workspace is then
written by the same ROOT version that reads it.

The statistical model mirrors `shared/sb_fit.py` exactly:
  * observable   m_lljj (m_lJ) restricted to the Stage-6 fit range, snapped to
                 the 100 GeV bin grid the way TH1::Fit selects bins (centers
                 inside [fit_lo, fit_hi]);
  * data_obs     the summed background MC in that range (from prepare_inputs);
  * background   the recentered falling shape, exp/powlaw with the [0]
                 normalization absorbed into a floating `bkg_pdf_norm`
                 (slope constrained <= 0 as in PAR_LIMITS);
  * signal       Gaussian(m_c, sigma) with both parameters constant -- the
                 same fixed shape the S+B fit uses.

Signal `rate` = expected events per **1 fb** of sigma x BR (lumi x eff), so the
POI is the cross section: r_UL == sigma_UL in fb.

Usage (inside or outside the container):
  python3 make_workspaces.py --channel ee --topology resolved \
      --functions expo --masses 2000
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import ROOT

ROOT.gROOT.SetBatch(True)
ROOT.RooMsgService.instance().setGlobalKillBelow(ROOT.RooFit.WARNING)

HERE = Path(__file__).resolve().parent

# RooGenericPdf formulas: shape-only versions of bkg_fit_lib.TF1_FORMULA (the
# exp([0]) / overall normalization is the pdf norm). One shape parameter each.
SHAPES = {
    "expo":   ("exp(@1*((@0-{m0})/1000.))", ("b_expo", -3.0, -100.0, 0.0)),
    "powlaw": ("pow(@0/{m0},@1)",           ("p_powlaw", -8.0, -100.0, 0.0)),
}

CARD = """\
# {tag}  m_WR={mass}  fn={fn}  (auto-generated by make_workspaces.py)
# window: [{lo:.1f}, {hi:.1f}] snapped to [{slo:.0f}, {shi:.0f}], m_c={m_c}, sigma={sigma}
# signal: {signal_tag}  eff={eff:.4f}  rate = lumi*eff = {rate:.4f} ev/fb -> r is sigma in fb
imax 1
jmax 1
kmax *
----------------
shapes sig       win  {ws} w:sig_pdf
shapes bkg       win  {ws} w:bkg_pdf
shapes data_obs  win  {ws} w:data_obs
----------------
bin          win
observation  -1
----------------
bin      win   win
process  sig   bkg
process  0     1
rate     {rate:.6g}  1
----------------
{shape_par} flatParam
bkg_pdf_norm flatParam
"""


def snap_range(h, lo, hi):
    """First/last bin whose center is inside [lo, hi] -- TH1::Fit's selection."""
    ax = h.GetXaxis()
    i0 = next(i for i in range(1, h.GetNbinsX() + 1) if ax.GetBinCenter(i) >= lo)
    i1 = next(i for i in range(h.GetNbinsX(), 0, -1) if ax.GetBinCenter(i) <= hi)
    return i0, i1


def build_one(h_full, m, fn, out_dir, tag):
    formula, (pname, pinit, plo, phi) = SHAPES[fn]
    i0, i1 = snap_range(h_full, m["fit_lo"], m["fit_hi"])
    slo, shi = (h_full.GetXaxis().GetBinLowEdge(i0),
                h_full.GetXaxis().GetBinUpEdge(i1))
    nbins = i1 - i0 + 1
    h_win = ROOT.TH1D("h_win", "", nbins, slo, shi)
    for i in range(nbins):
        h_win.SetBinContent(i + 1, h_full.GetBinContent(i0 + i))
    nobs = h_win.Integral()

    x = ROOT.RooRealVar("mass", "m [GeV]", slo, shi)
    x.setBins(nbins)
    data = ROOT.RooDataHist("data_obs", "", ROOT.RooArgList(x), h_win)

    par = ROOT.RooRealVar(pname, pname, pinit, plo, phi)
    bkg = ROOT.RooGenericPdf("bkg_pdf", formula.format(m0=f"{m['m_c']:.10g}"),
                             ROOT.RooArgList(x, par))
    norm = ROOT.RooRealVar("bkg_pdf_norm", "", nobs, 0.0, max(10.0 * nobs, 50.0))

    mu = ROOT.RooRealVar("mu_sig", "", m["m_c"])
    sg = ROOT.RooRealVar("sigma_sig", "", m["sigma"])
    mu.setConstant(True)
    sg.setConstant(True)
    sig = ROOT.RooGaussian("sig_pdf", "", x, mu, sg)

    w = ROOT.RooWorkspace("w", "w")
    for obj in (data, bkg, norm, sig):
        getattr(w, "import")(obj)

    mass_i = int(float(m["mass"]))
    ws_name = f"ws_{fn}_m{mass_i}.root"
    w.writeToFile(str(out_dir / ws_name))
    card = out_dir / f"card_{fn}_m{mass_i}.txt"
    card.write_text(CARD.format(
        tag=tag, mass=mass_i, fn=fn, ws=ws_name, shape_par=pname,
        lo=m["fit_lo"], hi=m["fit_hi"], slo=slo, shi=shi, m_c=m["m_c"],
        sigma=m["sigma"], signal_tag=m["signal_tag"], eff=m["eff"],
        rate=m["rate_per_fb"]))
    print(f"  {card.name}: bins [{slo:.0f},{shi:.0f}] ({nbins}), "
          f"B={nobs:.1f}, rate={m['rate_per_fb']:.2f} ev/fb")
    return card, mass_i


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--channel", default="ee")
    p.add_argument("--topology", default="resolved")
    p.add_argument("--functions", nargs="+", default=["expo", "powlaw"],
                   choices=list(SHAPES))
    p.add_argument("--masses", nargs="+", type=float, default=None,
                   help="default: every mass in the inputs JSON")
    p.add_argument("--run", default="run3", choices=["run2", "run3"],
                   help="run-label subdir for the default input/output dirs "
                        "(plain PyROOT here, so the era->run mapping cannot "
                        "be derived; pass explicitly)")
    p.add_argument("--observed", default="mc", choices=["mc", "data"],
                   help="observation: 'mc' = summed background MC (Asimov-"
                        "like), 'data' = the real data histogram dumped by "
                        "prepare_inputs --with-data")
    p.add_argument("--input-dir", type=Path, default=None)
    p.add_argument("--output-dir", type=Path, default=None)
    args = p.parse_args()
    if args.input_dir is None:
        args.input_dir = HERE / args.run / "inputs"
    if args.output_dir is None:
        args.output_dir = HERE / args.run / "cards"
    tag = f"{args.channel}_{args.topology}"

    with open(args.input_dir / f"{tag}.json") as fh:
        meta = json.load(fh)
    fin = ROOT.TFile(str(args.input_dir / f"{tag}.root"))
    hist_name = {"mc": "data_obs_full", "data": "data_obs_real"}[args.observed]
    h_full = fin.Get(hist_name)
    if not h_full:
        raise SystemExit(f"'{hist_name}' not in {args.input_dir / (tag + '.root')}"
                         " (for --observed data, rerun prepare_inputs"
                         " --with-data)")
    print(f"observation: {args.observed} ('{hist_name}',"
          f" {h_full.Integral():.0f} events)")

    wanted = None if args.masses is None else {f"{m:.0f}" for m in args.masses}
    out_dir = args.output_dir / tag
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest = []
    for key, m in sorted(meta["masses"].items(), key=lambda kv: float(kv[0])):
        if wanted is not None and key not in wanted:
            continue
        m = dict(m, mass=key)
        for fn in args.functions:
            card, mass_i = build_one(h_full, m, fn, out_dir, tag)
            manifest.append(f"{card}\t{mass_i}\t{fn}")
    (out_dir / "manifest.txt").write_text("\n".join(manifest) + "\n")
    print(f"{len(manifest)} cards -> {out_dir}/manifest.txt")


if __name__ == "__main__":
    main()
